"""empty message

Revision ID: 110c21f70b8c
Revises: 8b7b7556b5d3
Create Date: 2025-08-08 19:04:38.229588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110c21f70b8c'
down_revision = '8b7b7556b5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('perfil',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('perfil',
               existing_type=sa.String(length=6),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
